name: Spell Check Github Action
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Check spelling of file.txt
      uses: crate-ci/typos@master
      with: 
        files: ./README.md

    - name: Use custom config file
      uses: crate-ci/typos@master
      with: 
        files: ./README.md
        config: ./myconfig.toml

    - name: Ignore implicit configuration file
      uses: crate-ci/typos@master
      with: 
        files: ./README.md
        isolated: true

    - name: Writes changes in the local checkout
      uses: crate-ci/typos@master
      with: 
        write_changes: true
